//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 08:05:25 PM PDT 
//


package jp.tamagotchi.soap.transaction;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jp.tamagotchi.soap.transaction package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jp.tamagotchi.soap.transaction
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetTransactionsResponse }
     * 
     */
    public GetTransactionsResponse createGetTransactionsResponse() {
        return new GetTransactionsResponse();
    }

    /**
     * Create an instance of {@link GetTransactionRequest }
     * 
     */
    public GetTransactionRequest createGetTransactionRequest() {
        return new GetTransactionRequest();
    }

    /**
     * Create an instance of {@link GetTransactionResponse }
     * 
     */
    public GetTransactionResponse createGetTransactionResponse() {
        return new GetTransactionResponse();
    }

    /**
     * Create an instance of {@link Transaction }
     * 
     */
    public Transaction createTransaction() {
        return new Transaction();
    }

    /**
     * Create an instance of {@link GetTransactionsRequest }
     * 
     */
    public GetTransactionsRequest createGetTransactionsRequest() {
        return new GetTransactionsRequest();
    }

    /**
     * Create an instance of {@link SaveTransactionRequest }
     * 
     */
    public SaveTransactionRequest createSaveTransactionRequest() {
        return new SaveTransactionRequest();
    }

    /**
     * Create an instance of {@link SaveTransactionResponse }
     * 
     */
    public SaveTransactionResponse createSaveTransactionResponse() {
        return new SaveTransactionResponse();
    }

    /**
     * Create an instance of {@link GetTransactionsResponse.Data }
     * 
     */
    public GetTransactionsResponse.Data createGetTransactionsResponseData() {
        return new GetTransactionsResponse.Data();
    }

}
