//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.30 at 10:30:11 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tamagotchi.jp/soap/country", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package jp.tamagotchi.soap.country;
