//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.15 at 08:05:25 PM PDT 
//


package jp.tamagotchi.soap.pet;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jp.tamagotchi.soap.pet package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jp.tamagotchi.soap.pet
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetPetsResponse }
     * 
     */
    public GetPetsResponse createGetPetsResponse() {
        return new GetPetsResponse();
    }

    /**
     * Create an instance of {@link GetPetRequest }
     * 
     */
    public GetPetRequest createGetPetRequest() {
        return new GetPetRequest();
    }

    /**
     * Create an instance of {@link GetPetsResponse.Data }
     * 
     */
    public GetPetsResponse.Data createGetPetsResponseData() {
        return new GetPetsResponse.Data();
    }

    /**
     * Create an instance of {@link SavePetResponse }
     * 
     */
    public SavePetResponse createSavePetResponse() {
        return new SavePetResponse();
    }

    /**
     * Create an instance of {@link Pet }
     * 
     */
    public Pet createPet() {
        return new Pet();
    }

    /**
     * Create an instance of {@link GetPetsRequest }
     * 
     */
    public GetPetsRequest createGetPetsRequest() {
        return new GetPetsRequest();
    }

    /**
     * Create an instance of {@link GetPetResponse }
     * 
     */
    public GetPetResponse createGetPetResponse() {
        return new GetPetResponse();
    }

    /**
     * Create an instance of {@link SavePetRequest }
     * 
     */
    public SavePetRequest createSavePetRequest() {
        return new SavePetRequest();
    }

}
